### ISSUE TITLE
Doesn't work with GNU coreutils

### ISSUE THREAD

**Issue by RobertAudi** [dustinblackman/tcon#1]
The script uses `mktemp -t`:

https://github.com/dustinblackman/tcon/blob/1ccfc8c4321078081744886740b37aba3e2e95e8/tcon.sh#L24

The problem is that this assumes that it is using the BSD `mktemp` command, and with the GNU version the script fails with the following error:

```console
$ seq 1 10 | (while read f; do echo "echo 'Sleeping for $f seconds' && sleep $f"; done;) | tcon 4 -x
Starting up tmux panes with a concurrency of 4
mktemp: too few X's in template ‘tcon-fifo’
```

That's because GNU `mktemp`'s `-t` option takes a template instead of a prefix.

**Comment by dustinblackman** [comment]
Got it, thanks! Fixed in https://github.com/dustinblackman/tcon/commit/ab5d41631a27e677df7c0cfcfb42537abefe321f

**Comment by RobertAudi** [comment]
@dustinblackman My pleasure.  I was going to make a pull request to address the issue but I didn't have the time (I didn't take the time :expressionless:).

Thanks a lot for the quick response time though, and more importantly thank you for this awesome project!
